secret_key_base: EvzcTbz_8tcarTIN7mwZByvxZj3Tqewk_JY5xd-lgTc
port: 3000
name: example_app_amber
log: "::Logger.new(STDOUT)"
log_level: "::Logger::INFO"
color: true
host: 0.0.0.0
port_reuse: false
process_count: (ENV[%(AMBER_PROCESS_COUNT)]? || 1).to_i
ssl_key_file:
ssl_cert_file:
redis_url: "redis://localhost:6379"
session:
  key: amber.session
  store: :signed_cookie
  expires: 0
secrets:
  description: Store your development secrets credentials and settings here.
  database: postgres://postgres:@localhost:5432/example_app_amber_development
